spring:
#  application:
#    name: store
  datasource:
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: true
    hibernate:
      ddl-auto: update
#  jwt:
#    secret: ${JWT_SECRET}
#    accessTokenExpiration: 7200 # 15 mins=900, 1hr=7200
#    refreshTokenExpiration: 604800 #7 days
  flyway:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
#stripe:
#  secretKey: ${STRIPE_SECRET_KEY}
#  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:4242